Fix "git pile format-patch" failure if git-pile installed with "--user"
Environment: Ubuntu 16.04

This problem does not occur if git-pile is installed via:
    $ sudo ./setup.py install
but does occur if installed via:
    $ ./setup.py install --user

When I attempted to do:
    $ git pile format-patch -o ../psp
It failed with:
    fatal: failed to read orderfile '/home/username/.local/lib/python3.5/site-packages/git_pile-0.9-py3.5.egg/git_pile/data/git-cover-order.txt': Not a directory

Diagnosis: the "setuptools" "./setup.py --user" installation is not "zip_safe".

Solution: Add "zip_safe = False" as a parameter of function "setup" in file "setup.py".

Background:

In file git_pile/git_pile.py:784 there is the following statement:
        order_file = op.join(op.dirname(op.realpath(__file__)),
                             "data", "git-cover-order.txt")

This is an attempt to get a path to file git-cover-order.txt that may
be used with a subsequent "git diff" command.  In this case (but only if
installed with "--user"), "__file__" refers not to a directory, but to file
"git_pile-0.9-py3.5.egg" which is a zip archive that contains the desired file.
For some uses of setuptools where access to the file would be done through
python API, this would be OK.  In this case, the file must exist in the
regular filesystem so that the "git diff" command can find it.

Further evidence:

Command fails:
    $ git pile format-patch -o ../psp

But the above will work if setup.py is modified to have
"zip_safe = False" as an arg to function "setup".

Command executed directly from the git-pile" repository works:
    $ /home/username/gfx/r/git-pile/git-pile format-patch -o ../psp

The above command correctly accesses the desired file via the "git diff" from:
    /home/username/gfx/r/git-pile/git_pile/data/git-cover-order.txt

The following log shows (with "--debug" specified) first the failing command,
and the command executed from the git-pile repo:

$ git pile format-patch --debug -o ../psp
+ git --exec-path
+ git config --get-regex 'pile\.*'
+ git rev-parse --git-common-dir
+ git -C .git/.. rev-parse --show-toplevel
+ git show-ref --verify --quiet refs/heads/HEAD
+ git symbolic-ref --short -q HEAD
+ git rev-parse --abbrev-ref 'HEAD@{u}'
+ git range-diff --no-color --no-patch a76fa4d02cc806e30ed72ba1b8233c694ab1727b..origin/internal a76fa4d02cc806e30ed72ba1b8233c694ab1727b..u1
+ git log --format=%f --reverse -1 522f15f0
+ git log --format=%f --reverse -1 20771cd7
+ git worktree add --detach --checkout /home/username/bt/igt/igt-gpu-tools/.git-pile-worktreec0uq0qpp pile
+ git rev-list --reverse a76fa4d02cc806e30ed72ba1b8233c694ab1727b..u1
+ git log --format=%f --reverse a76fa4d02cc806e30ed72ba1b8233c694ab1727b..u1
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 8c7ec3578be368015f8c564d719918f81fbcd61c
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 1a521306f856697042a94442155eec9d16ed34d3
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 16f8ace31d1229c06f7995e2f716abd115924f9f
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 21a56124545ed8d2b220bddaeb25778b3ee2ad78
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 74b9449ba3cb2db4c5bdf54bfc34a5cd2a5fac98
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 a3db0f62ed862631c80e3c6b48c18b364bf6262a
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 93229e4b0220173ec575033f04be28e0e4b0897e
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 9e8c0f7e041c45fcbacc4536c7d3df8042347a03
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 b4e2f3a324311f15d11c5a07990e11733161d51a
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 1205f2a64b235d4e88d1fc0feacf8597cd2ad556
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 fec9ec55d38b94579eed5b48efededf1827af042
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 6bf9792c2a8fc11953af3e86bab4d8b926b781ae
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 44791dc4379470bf5f99cb43f164067a9f950cfa
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 0b14693a47ddcd0ca2f606a368500c09afddbdf8
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 1496cff900956d3db0aba048eef5ece03b5b81f7
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 84388a6f6d3015f26f9a69a76f0f2b70f4b0a318
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 9df59b4e36e20487d754243ec5b839c817bffe6c
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 f473035b8552863b6efe84b61e3c7bf2d0a70ee4
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 522f15f09cac58bc29cf5edb92fb459f522b0963
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 20771cd7c5a1564e758bc3ccd901321df75dc4ec
+ git rev-parse a76fa4d02cc806e30ed72ba1b8233c694ab1727b
+ git -C /home/username/bt/igt/igt-gpu-tools/.git-pile-worktreec0uq0qpp add -A
+ git -C /home/username/bt/igt/igt-gpu-tools/.git-pile-worktreec0uq0qpp diff --cached -p --stat -O /home/username/.local/lib/python3.5/site-packages/git_pile-0.9-py3.5.egg/git_pile/data/git-cover-order.txt -- config 0001-tests-i915-gem_ctx_isolation.c-enable-test-through-G.patch series
fatal: failed to read orderfile '/home/username/.local/lib/python3.5/site-packages/git_pile-0.9-py3.5.egg/git_pile/data/git-cover-order.txt': Not a directory
+ git worktree remove /home/username/bt/igt/igt-gpu-tools/.git-pile-worktreec0uq0qpp
Traceback (most recent call last):
  File "/home/username/.local/bin/git-pile", line 4, in <module>
    __import__('pkg_resources').run_script('git-pile==0.9', 'git-pile')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/username/.local/lib/python3.5/site-packages/git_pile-0.9-py3.5.egg/EGG-INFO/scripts/git-pile", line 10, in <module>
  File "/home/username/.local/lib/python3.5/site-packages/git_pile-0.9-py3.5.egg/git_pile/git_pile.py", line 1165, in main
  File "/home/username/.local/lib/python3.5/site-packages/git_pile-0.9-py3.5.egg/git_pile/git_pile.py", line 787, in cmd_format_patch
  File "/home/username/.local/lib/python3.5/site-packages/git_pile-0.9-py3.5.egg/git_pile/helpers.py", line 62, in __call__
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', '-C', '/home/username/bt/igt/igt-gpu-tools/.git-pile-worktreec0uq0qpp', 'diff', '--cached', '-p', '--stat', '-O', '/home/username/.local/lib/python3.5/site-packages/git_pile-0.9-py3.5.egg/git_pile/data/git-cover-order.txt', '--', 'config', '0001-tests-i915-gem_ctx_isolation.c-enable-test-through-G.patch', 'series']' returned non-zero exit status 128

$ /home/username/gfx/r/git-pile/git-pile format-patch --debug -o ../psp
+ git --exec-path
+ git config --get-regex 'pile\.*'
+ git rev-parse --git-common-dir
+ git -C .git/.. rev-parse --show-toplevel
+ git show-ref --verify --quiet refs/heads/HEAD
+ git symbolic-ref --short -q HEAD
+ git rev-parse --abbrev-ref 'HEAD@{u}'
+ git range-diff --no-color --no-patch a76fa4d02cc806e30ed72ba1b8233c694ab1727b..origin/internal a76fa4d02cc806e30ed72ba1b8233c694ab1727b..u1
+ git log --format=%f --reverse -1 522f15f0
+ git log --format=%f --reverse -1 20771cd7
+ git worktree add --detach --checkout /home/username/bt/igt/igt-gpu-tools/.git-pile-worktreehxs9cskg pile
+ git rev-list --reverse a76fa4d02cc806e30ed72ba1b8233c694ab1727b..u1
+ git log --format=%f --reverse a76fa4d02cc806e30ed72ba1b8233c694ab1727b..u1
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 8c7ec3578be368015f8c564d719918f81fbcd61c
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 1a521306f856697042a94442155eec9d16ed34d3
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 16f8ace31d1229c06f7995e2f716abd115924f9f
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 21a56124545ed8d2b220bddaeb25778b3ee2ad78
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 74b9449ba3cb2db4c5bdf54bfc34a5cd2a5fac98
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 a3db0f62ed862631c80e3c6b48c18b364bf6262a
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 93229e4b0220173ec575033f04be28e0e4b0897e
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 9e8c0f7e041c45fcbacc4536c7d3df8042347a03
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 b4e2f3a324311f15d11c5a07990e11733161d51a
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 1205f2a64b235d4e88d1fc0feacf8597cd2ad556
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 fec9ec55d38b94579eed5b48efededf1827af042
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 6bf9792c2a8fc11953af3e86bab4d8b926b781ae
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 44791dc4379470bf5f99cb43f164067a9f950cfa
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 0b14693a47ddcd0ca2f606a368500c09afddbdf8
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 1496cff900956d3db0aba048eef5ece03b5b81f7
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 84388a6f6d3015f26f9a69a76f0f2b70f4b0a318
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 9df59b4e36e20487d754243ec5b839c817bffe6c
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 f473035b8552863b6efe84b61e3c7bf2d0a70ee4
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 522f15f09cac58bc29cf5edb92fb459f522b0963
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= --stdout -N -1 20771cd7c5a1564e758bc3ccd901321df75dc4ec
+ git rev-parse a76fa4d02cc806e30ed72ba1b8233c694ab1727b
+ git -C /home/username/bt/igt/igt-gpu-tools/.git-pile-worktreehxs9cskg add -A
+ git -C /home/username/bt/igt/igt-gpu-tools/.git-pile-worktreehxs9cskg diff --cached -p --stat -O /home/username/gfx/r/git-pile/git_pile/data/git-cover-order.txt -- series 0001-tests-i915-gem_ctx_isolation.c-enable-test-through-G.patch config
+ git worktree remove /home/username/bt/igt/igt-gpu-tools/.git-pile-worktreehxs9cskg
+ git config --get format.subjectprefix
+ git rev-parse pile
+ git config --get user.name
+ git config --get user.email
../psp/0000-cover-letter.patch
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= -o /tmp/tmp_ak3pfs1 -N -1 522f15f0
../psp/0001-tests-i915-gem_ctx_isolation.c-enable-test-through-G.patch
+ git format-patch --subject-prefix=PATCH --zero-commit --signature= -o /tmp/tmp_ak3pfs1 -N -1 20771cd7
../psp/0002-tests-i915-gem_ctx_isolation.c-enable-test-through-G.patch

Signed-off-by: Dale Stimson <dale.b.stimson@intel.com>