github: Install missing tools
Fix error from CI:

	Run python3 -m pip install --user --no-use-pep517 --editable .[tests]

	Usage:
	  /__t/Python/3.10.14/x64/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
	  /__t/Python/3.10.14/x64/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
	  /__t/Python/3.10.14/x64/bin/python3 -m pip install [options] [-e] <vcs project url> ...
	  /__t/Python/3.10.14/x64/bin/python3 -m pip install [options] [-e] <local project path> ...
	  /__t/Python/3.10.14/x64/bin/python3 -m pip install [options] <archive url/path> ...

	--no-use-pep517 error: It is not possible to use --no-use-pep517
	without setuptools and wheel installed.
	Error: Process completed with exit code 2.

Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>