git-pile: fix config regex
Only parse configuration starting with pile, i.e. those that are inside
a "[pile]" group. Otherwise we would parse things like branch.pile.remote.
It gets worse when we have aliases with pile in the name that may make
git pile to explode:

Traceback (most recent call last):
  File "/home/lucasdemarchi/.local/bin/git-pile", line 4, in <module>
    __import__('pkg_resources').run_script('git-pile==0.91', 'git-pile')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/lucasdemarchi/.local/lib/python3.7/site-packages/git_pile-0.91-py3.7.egg/EGG-INFO/scripts/git-pi
le", line 10, in <module>
    sys.exit(git_pile.main(*sys.argv[1:]))
  File "/home/lucasdemarchi/.local/lib/python3.7/site-packages/git_pile-0.91-py3.7.egg/git_pile/git_pile.py",
line 1314, in main
    return args.func(args)
  File "/home/lucasdemarchi/.local/lib/python3.7/site-packages/git_pile-0.91-py3.7.egg/git_pile/git_pile.py",
line 996, in cmd_baseline
    config = Config()
  File "/home/lucasdemarchi/.local/lib/python3.7/site-packages/git_pile-0.91-py3.7.egg/git_pile/git_pile.py",
line 63, in __init__
    key, value = kv.strip().split()
ValueError: too many values to unpack (expected 2)

Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>