am: fix calling cmd_genbranch on missing inplace arg
Fake it, like in the other args:

Traceback (most recent call last):
  File "/home/aswarup/.local/bin/git-pile", line 4, in <module>
    __import__('pkg_resources').run_script('git-pile==0.94', 'git-pile')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/aswarup/.local/lib/python3.6/site-packages/git_pile-0.94-py3.6.egg/EGG-INFO/scripts/git-pile", line 10, in <module>
    sys.exit(git_pile.main(*sys.argv[1:]))
  File "/home/aswarup/.local/lib/python3.6/site-packages/git_pile-0.94-py3.6.egg/git_pile/git_pile.py", line 1554, in main
    return args.func(args)
  File "/home/aswarup/.local/lib/python3.6/site-packages/git_pile-0.94-py3.6.egg/git_pile/git_pile.py", line 879, in cmd_am
    return cmd_genbranch(args)
  File "/home/aswarup/.local/lib/python3.6/site-packages/git_pile-0.94-py3.6.egg/git_pile/git_pile.py", line 1107, in cmd_genbranch
    if args.inplace:
AttributeError: 'Namespace' object has no attribute 'inplace'

Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>