mbox-prepare: fix style checks
Several minor formatting checks were failing:

class Patch:
^
./tests/test_mbox_prepare.py:4:1: F401 'os' imported but unused
import os
^
./tests/test_mbox_prepare.py:9:1: F401 'nose.tools.with_setup' imported but unused
from nose.tools import assert_equal, assert_raises, with_setup
^
./tests/test_mbox_prepare.py:102:1: E302 expected 2 blank lines, found 1
def test_mbox_rfc():
^
./tests/test_mbox_prepare.py:102:1: F811 redefinition of unused 'test_mbox_rfc' from line 91
def test_mbox_rfc():
^
./tests/test_mbox_prepare.py:113:1: E302 expected 2 blank lines, found 1
def test_mbox_interactive_fail():
^
./tests/test_mbox_prepare.py:124:1: E265 block comment should start with '# '
^
./tests/test_mbox_prepare.py:127:1: E265 block comment should start with '# '
^
./tests/test_mbox_prepare.py:128:1: E265 block comment should start with '# '
^

Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>