genlinear-branch: Fix missing pile_range
	[igt-gpu-tools]$ git pile genlinear-branch -b internal-linear
	Traceback (most recent call last):
	  File "/home/adixit/.local/bin/git-pile", line 4, in <module>
	    __import__('pkg_resources').run_script('git-pile==1.0.dev0', 'git-pile')
	  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
	    self.require(requires)[0].run_script(script_name, ns)
	  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1453, in run_script
	    exec(code, namespace, namespace)
	  File "/home/adixit/.local/lib/python3.10/site-packages/git_pile-1.0.dev0-py3.10.egg/EGG-INFO/scripts/git-pile", line 12, in <module>
	    sys.exit(git_pile.main(*sys.argv[1:]))
	  File "/home/adixit/.local/lib/python3.10/site-packages/git_pile-1.0.dev0-py3.10.egg/git_pile/git_pile.py", line 2432, in main
	    return args.func(args, config)
	  File "/home/adixit/.local/lib/python3.10/site-packages/git_pile-1.0.dev0-py3.10.egg/git_pile/git_pile.py", line 1698, in cmd_genlinear_branch
	    parent_ref, pile_range = get_refs_from_linearized(args.incremental, config.pile_branch, args.start_ref, branch, notes_ref)
	  File "/home/adixit/.local/lib/python3.10/site-packages/git_pile-1.0.dev0-py3.10.egg/git_pile/git_pile.py", line 1660, in get_refs_from_linearized
	    return None, pile_range
	UnboundLocalError: local variable 'pile_range' referenced before assignment

When commit 6171f65cfeaf ("genlinear-branch: Allow to override first commit") added an option
to override the start commit, it didn't handle well when start_ref is None.

Fix: 6171f65cfeaf ("genlinear-branch: Allow to override first commit")
Fix: #90
Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>