git-pile: fix missing quiet arg on genbranch
When we apply a patch with the -g option, we end up calling
cmd_genbranch() as a second subcommand. Any option added to
cmd_genbranch() needs to be set otherwise it fails with:

	‣ Generating branch 'staging'
	Traceback (most recent call last):
	  File "/home/lucasdemarchi/.local/bin/git-pile", line 4, in <module>
	    __import__('pkg_resources').run_script('git-pile==0.92', 'git-pile')
	  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
	    self.require(requires)[0].run_script(script_name, ns)
	  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
	    exec(code, namespace, namespace)
	  File "/home/lucasdemarchi/.local/lib/python3.7/site-packages/git_pile-0.92-py3.7.egg/EGG-INFO/scripts/git-pile", line 10, in <module>
	    sys.exit(git_pile.main(*sys.argv[1:]))
	  File "/home/lucasdemarchi/.local/lib/python3.7/site-packages/git_pile-0.92-py3.7.egg/git_pile/git_pile.py", line 1395, in main
	    return args.func(args)
	  File "/home/lucasdemarchi/.local/lib/python3.7/site-packages/git_pile-0.92-py3.7.egg/git_pile/git_pile.py", line 838, in cmd_am
	    return cmd_genbranch(args)
	  File "/home/lucasdemarchi/.local/lib/python3.7/site-packages/git_pile-0.92-py3.7.egg/git_pile/git_pile.py", line 1049, in cmd_genbranch
	    stdout = nul_f if args.quiet else sys.stdout
	AttributeError: 'Namespace' object has no attribute 'quiet'

Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>