git-pile: decode only "From:" and "Subject:" headers
This avoids the problem of unknown bytes added by smtp servers to the
message. We control that the pile coverletter is on UTF-8, but we don't
control what they added.

Fix explosion with the following header:
	Received: (from xxxx@xxxxx)  by xxxx.xx.xxxx.xxxx with <9c> id
	 x7M42god001101;        Wed, 21 Aug 2019 21:02:42 -0700

Producing the following trace:
	Traceback (most recent call last):
	  File "/home/lucasdemarchi/.local/lib/python3.6/site-packages/git_pile-0.92-py3.6.egg/git_pile/git_pile.py", line 787, in dump
	    v = v.decode(*([vencoding] if vencoding else []))
	LookupError: unknown encoding: unknown-8bit

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/home/lucasdemarchi/.local/bin/git-pile", line 4, in <module>
	    __import__('pkg_resources').run_script('git-pile==0.92', 'git-pile')
	  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
	    self.require(requires)[0].run_script(script_name, ns)
	  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
	    exec(code, namespace, namespace)
	  File "/home/lucasdemarchi/.local/lib/python3.6/site-packages/git_pile-0.92-py3.6.egg/EGG-INFO/scripts/git-pile", line 10, in <module>
	    sys.exit(git_pile.main(*sys.argv[1:]))
	  File "/home/lucasdemarchi/.local/lib/python3.6/site-packages/git_pile-0.92-py3.6.egg/git_pile/git_pile.py", line 1394, in main
	    return args.func(args)
	  File "/home/lucasdemarchi/.local/lib/python3.6/site-packages/git_pile-0.92-py3.6.egg/git_pile/git_pile.py", line 821, in cmd_am
	    cover.dump(proc.stdin)
	  File "/home/lucasdemarchi/.local/lib/python3.6/site-packages/git_pile-0.92-py3.6.egg/git_pile/git_pile.py", line 792, in dump
	    v = v.decode('utf-8')
	UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 59: invalid start byte

The only headers we care about to keep intact are "Subject" and "From",
so only try to decode those.

Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>